apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: edgemesh-prod
namePrefix: prod-

resources:
  - ../../base

commonLabels:
  app.kubernetes.io/instance: edgemesh-prod
  environment: production

replicas:
  - name: app-with-edgemesh
    count: 3
