apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: edgemesh-stg
namePrefix: stg-

resources:
  - ../../base

commonLabels:
  app.kubernetes.io/instance: edgemesh-stg
  environment: staging

replicas:
  - name: app-with-edgemesh
    count: 2
