// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: edgemesh/mesh.proto

package edgemeshpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Health int32

const (
	Health_HEALTH_UNKNOWN   Health = 0
	Health_HEALTH_HEALTHY   Health = 1
	Health_HEALTH_UNHEALTHY Health = 2
)

// Enum value maps for Health.
var (
	Health_name = map[int32]string{
		0: "HEALTH_UNKNOWN",
		1: "HEALTH_HEALTHY",
		2: "HEALTH_UNHEALTHY",
	}
	Health_value = map[string]int32{
		"HEALTH_UNKNOWN":   0,
		"HEALTH_HEALTHY":   1,
		"HEALTH_UNHEALTHY": 2,
	}
)

func (x Health) Enum() *Health {
	p := new(Health)
	*p = x
	return p
}

func (x Health) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Health) Descriptor() protoreflect.EnumDescriptor {
	return file_edgemesh_mesh_proto_enumTypes[0].Descriptor()
}

func (Health) Type() protoreflect.EnumType {
	return &file_edgemesh_mesh_proto_enumTypes[0]
}

func (x Health) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Health.Descriptor instead.
func (Health) EnumDescriptor() ([]byte, []int) {
	return file_edgemesh_mesh_proto_rawDescGZIP(), []int{0}
}

type ListPeersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"` // optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPeersRequest) Reset() {
	*x = ListPeersRequest{}
	mi := &file_edgemesh_mesh_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPeersRequest) ProtoMessage() {}

func (x *ListPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_edgemesh_mesh_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPeersRequest.ProtoReflect.Descriptor instead.
func (*ListPeersRequest) Descriptor() ([]byte, []int) {
	return file_edgemesh_mesh_proto_rawDescGZIP(), []int{0}
}

func (x *ListPeersRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type ListPeersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*PeerStatus          `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPeersResponse) Reset() {
	*x = ListPeersResponse{}
	mi := &file_edgemesh_mesh_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPeersResponse) ProtoMessage() {}

func (x *ListPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_edgemesh_mesh_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPeersResponse.ProtoReflect.Descriptor instead.
func (*ListPeersResponse) Descriptor() ([]byte, []int) {
	return file_edgemesh_mesh_proto_rawDescGZIP(), []int{1}
}

func (x *ListPeersResponse) GetPeers() []*PeerStatus {
	if x != nil {
		return x.Peers
	}
	return nil
}

type GetPeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeerRequest) Reset() {
	*x = GetPeerRequest{}
	mi := &file_edgemesh_mesh_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeerRequest) ProtoMessage() {}

func (x *GetPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_edgemesh_mesh_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeerRequest.ProtoReflect.Descriptor instead.
func (*GetPeerRequest) Descriptor() ([]byte, []int) {
	return file_edgemesh_mesh_proto_rawDescGZIP(), []int{2}
}

func (x *GetPeerRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

type PeerStatus struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	PeerId               string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Service              string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Address              string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Health               Health                 `protobuf:"varint,4,opt,name=health,proto3,enum=edgemesh.v1.Health" json:"health,omitempty"`
	LastProbeUnixNano    int64                  `protobuf:"varint,5,opt,name=last_probe_unix_nano,json=lastProbeUnixNano,proto3" json:"last_probe_unix_nano,omitempty"`
	ConsecutiveSuccesses uint32                 `protobuf:"varint,6,opt,name=consecutive_successes,json=consecutiveSuccesses,proto3" json:"consecutive_successes,omitempty"`
	ConsecutiveFailures  uint32                 `protobuf:"varint,7,opt,name=consecutive_failures,json=consecutiveFailures,proto3" json:"consecutive_failures,omitempty"`
	InFlight             uint32                 `protobuf:"varint,8,opt,name=in_flight,json=inFlight,proto3" json:"in_flight,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PeerStatus) Reset() {
	*x = PeerStatus{}
	mi := &file_edgemesh_mesh_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerStatus) ProtoMessage() {}

func (x *PeerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_edgemesh_mesh_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerStatus.ProtoReflect.Descriptor instead.
func (*PeerStatus) Descriptor() ([]byte, []int) {
	return file_edgemesh_mesh_proto_rawDescGZIP(), []int{3}
}

func (x *PeerStatus) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *PeerStatus) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *PeerStatus) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PeerStatus) GetHealth() Health {
	if x != nil {
		return x.Health
	}
	return Health_HEALTH_UNKNOWN
}

func (x *PeerStatus) GetLastProbeUnixNano() int64 {
	if x != nil {
		return x.LastProbeUnixNano
	}
	return 0
}

func (x *PeerStatus) GetConsecutiveSuccesses() uint32 {
	if x != nil {
		return x.ConsecutiveSuccesses
	}
	return 0
}

func (x *PeerStatus) GetConsecutiveFailures() uint32 {
	if x != nil {
		return x.ConsecutiveFailures
	}
	return 0
}

func (x *PeerStatus) GetInFlight() uint32 {
	if x != nil {
		return x.InFlight
	}
	return 0
}

type DrainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GraceSeconds  uint32                 `protobuf:"varint,1,opt,name=grace_seconds,json=graceSeconds,proto3" json:"grace_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainRequest) Reset() {
	*x = DrainRequest{}
	mi := &file_edgemesh_mesh_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainRequest) ProtoMessage() {}

func (x *DrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_edgemesh_mesh_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainRequest.ProtoReflect.Descriptor instead.
func (*DrainRequest) Descriptor() ([]byte, []int) {
	return file_edgemesh_mesh_proto_rawDescGZIP(), []int{4}
}

func (x *DrainRequest) GetGraceSeconds() uint32 {
	if x != nil {
		return x.GraceSeconds
	}
	return 0
}

type DrainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainResponse) Reset() {
	*x = DrainResponse{}
	mi := &file_edgemesh_mesh_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainResponse) ProtoMessage() {}

func (x *DrainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_edgemesh_mesh_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainResponse.ProtoReflect.Descriptor instead.
func (*DrainResponse) Descriptor() ([]byte, []int) {
	return file_edgemesh_mesh_proto_rawDescGZIP(), []int{5}
}

func (x *DrainResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *DrainResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ForwardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardRequest) Reset() {
	*x = ForwardRequest{}
	mi := &file_edgemesh_mesh_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardRequest) ProtoMessage() {}

func (x *ForwardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_edgemesh_mesh_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardRequest.ProtoReflect.Descriptor instead.
func (*ForwardRequest) Descriptor() ([]byte, []int) {
	return file_edgemesh_mesh_proto_rawDescGZIP(), []int{6}
}

func (x *ForwardRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ForwardRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ForwardRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ForwardRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ForwardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Attempts      uint32                 `protobuf:"varint,2,opt,name=attempts,proto3" json:"attempts,omitempty"`
	PeerId        string                 `protobuf:"bytes,3,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardResponse) Reset() {
	*x = ForwardResponse{}
	mi := &file_edgemesh_mesh_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardResponse) ProtoMessage() {}

func (x *ForwardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_edgemesh_mesh_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardResponse.ProtoReflect.Descriptor instead.
func (*ForwardResponse) Descriptor() ([]byte, []int) {
	return file_edgemesh_mesh_proto_rawDescGZIP(), []int{7}
}

func (x *ForwardResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ForwardResponse) GetAttempts() uint32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *ForwardResponse) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

var File_edgemesh_mesh_proto protoreflect.FileDescriptor

const file_edgemesh_mesh_proto_rawDesc = "" +
	"\n" +
	"\x13edgemesh/mesh.proto\x12\vedgemesh.v1\",\n" +
	"\x10ListPeersRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"B\n" +
	"\x11ListPeersResponse\x12-\n" +
	"\x05peers\x18\x01 \x03(\v2\x17.edgemesh.v1.PeerStatusR\x05peers\")\n" +
	"\x0eGetPeerRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\"\xbc\x02\n" +
	"\n" +
	"PeerStatus\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12+\n" +
	"\x06health\x18\x04 \x01(\x0e2\x13.edgemesh.v1.HealthR\x06health\x12/\n" +
	"\x14last_probe_unix_nano\x18\x05 \x01(\x03R\x11lastProbeUnixNano\x123\n" +
	"\x15consecutive_successes\x18\x06 \x01(\rR\x14consecutiveSuccesses\x121\n" +
	"\x14consecutive_failures\x18\a \x01(\rR\x13consecutiveFailures\x12\x1b\n" +
	"\tin_flight\x18\b \x01(\rR\binFlight\"3\n" +
	"\fDrainRequest\x12#\n" +
	"\rgrace_seconds\x18\x01 \x01(\rR\fgraceSeconds\"9\n" +
	"\rDrainResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xe0\x01\n" +
	"\x0eForwardRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12E\n" +
	"\bmetadata\x18\x04 \x03(\v2).edgemesh.v1.ForwardRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"`\n" +
	"\x0fForwardResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12\x1a\n" +
	"\battempts\x18\x02 \x01(\rR\battempts\x12\x17\n" +
	"\apeer_id\x18\x03 \x01(\tR\x06peerId*F\n" +
	"\x06Health\x12\x12\n" +
	"\x0eHEALTH_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eHEALTH_HEALTHY\x10\x01\x12\x14\n" +
	"\x10HEALTH_UNHEALTHY\x10\x022\x99\x02\n" +
	"\x04Mesh\x12J\n" +
	"\tListPeers\x12\x1d.edgemesh.v1.ListPeersRequest\x1a\x1e.edgemesh.v1.ListPeersResponse\x12?\n" +
	"\aGetPeer\x12\x1b.edgemesh.v1.GetPeerRequest\x1a\x17.edgemesh.v1.PeerStatus\x12>\n" +
	"\x05Drain\x12\x19.edgemesh.v1.DrainRequest\x1a\x1a.edgemesh.v1.DrainResponse\x12D\n" +
	"\aForward\x12\x1b.edgemesh.v1.ForwardRequest\x1a\x1c.edgemesh.v1.ForwardResponseB5Z3github.com/SAY-5/edgemesh/proto/edgemesh;edgemeshpbb\x06proto3"

var (
	file_edgemesh_mesh_proto_rawDescOnce sync.Once
	file_edgemesh_mesh_proto_rawDescData []byte
)

func file_edgemesh_mesh_proto_rawDescGZIP() []byte {
	file_edgemesh_mesh_proto_rawDescOnce.Do(func() {
		file_edgemesh_mesh_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_edgemesh_mesh_proto_rawDesc), len(file_edgemesh_mesh_proto_rawDesc)))
	})
	return file_edgemesh_mesh_proto_rawDescData
}

var file_edgemesh_mesh_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_edgemesh_mesh_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_edgemesh_mesh_proto_goTypes = []any{
	(Health)(0),               // 0: edgemesh.v1.Health
	(*ListPeersRequest)(nil),  // 1: edgemesh.v1.ListPeersRequest
	(*ListPeersResponse)(nil), // 2: edgemesh.v1.ListPeersResponse
	(*GetPeerRequest)(nil),    // 3: edgemesh.v1.GetPeerRequest
	(*PeerStatus)(nil),        // 4: edgemesh.v1.PeerStatus
	(*DrainRequest)(nil),      // 5: edgemesh.v1.DrainRequest
	(*DrainResponse)(nil),     // 6: edgemesh.v1.DrainResponse
	(*ForwardRequest)(nil),    // 7: edgemesh.v1.ForwardRequest
	(*ForwardResponse)(nil),   // 8: edgemesh.v1.ForwardResponse
	nil,                       // 9: edgemesh.v1.ForwardRequest.MetadataEntry
}
var file_edgemesh_mesh_proto_depIdxs = []int32{
	4, // 0: edgemesh.v1.ListPeersResponse.peers:type_name -> edgemesh.v1.PeerStatus
	0, // 1: edgemesh.v1.PeerStatus.health:type_name -> edgemesh.v1.Health
	9, // 2: edgemesh.v1.ForwardRequest.metadata:type_name -> edgemesh.v1.ForwardRequest.MetadataEntry
	1, // 3: edgemesh.v1.Mesh.ListPeers:input_type -> edgemesh.v1.ListPeersRequest
	3, // 4: edgemesh.v1.Mesh.GetPeer:input_type -> edgemesh.v1.GetPeerRequest
	5, // 5: edgemesh.v1.Mesh.Drain:input_type -> edgemesh.v1.DrainRequest
	7, // 6: edgemesh.v1.Mesh.Forward:input_type -> edgemesh.v1.ForwardRequest
	2, // 7: edgemesh.v1.Mesh.ListPeers:output_type -> edgemesh.v1.ListPeersResponse
	4, // 8: edgemesh.v1.Mesh.GetPeer:output_type -> edgemesh.v1.PeerStatus
	6, // 9: edgemesh.v1.Mesh.Drain:output_type -> edgemesh.v1.DrainResponse
	8, // 10: edgemesh.v1.Mesh.Forward:output_type -> edgemesh.v1.ForwardResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_edgemesh_mesh_proto_init() }
func file_edgemesh_mesh_proto_init() {
	if File_edgemesh_mesh_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_edgemesh_mesh_proto_rawDesc), len(file_edgemesh_mesh_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_edgemesh_mesh_proto_goTypes,
		DependencyIndexes: file_edgemesh_mesh_proto_depIdxs,
		EnumInfos:         file_edgemesh_mesh_proto_enumTypes,
		MessageInfos:      file_edgemesh_mesh_proto_msgTypes,
	}.Build()
	File_edgemesh_mesh_proto = out.File
	file_edgemesh_mesh_proto_goTypes = nil
	file_edgemesh_mesh_proto_depIdxs = nil
}
