apiVersion: v1
kind: Service
metadata:
  name: edgemesh-sidecar
  labels:
    app.kubernetes.io/name: edgemesh
    app.kubernetes.io/component: sidecar
spec:
  selector:
    app.kubernetes.io/name: edgemesh
    app.kubernetes.io/component: sidecar
  ports:
    - name: grpc
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
